### ISSUE TITLE
Is there an issue in the update_prototype_weight function?

### ISSUE THREAD

**Issue by yslanprime** [zzz47zzz/awesome-lifelong-learning-methods-for-llm#1]
In line 686 of the SEQ.py:
` cnt_class_samples[class_idx] += 1` 
should it instead be
` num_samples_in_batch = class_mask.sum().item()` ?

**Comment by zzz47zzz** [comment]
Thank you for thoroughly reviewing our code. This is indeed a mistake when computing the prototypes. We will fix it soon.

**Comment by yslanprime** [comment]
I apologize, I realized that my issue was submitted to the wrong repository. I hope you can understand.

> Thank you for thoroughly reviewing our code. This is indeed a mistake when computing the prototypes. We will fix it soon.
